## For students: change this path to the root of your code
CODEROOT = /home/anish/cs222_project/codebase
#CODEROOT= /home/nceglia/development/cs222_project/codebase
#CC = gcc
CC = g++

#CPPFLAGS = -Wall -I$(CODEROOT) -g     # with debugging info
CPPFLAGS = -Wall -I$(CODEROOT) -g -std=c++0x  # with debugging info and the C++11 feature
